# Generated by Django 2.2.1 on 2019-07-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingsApi', '0002_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritething',
            name='meta_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
