# Generated by Django 2.2.1 on 2019-07-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingsApi', '0003_auto_20190702_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritething',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
